//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAEICS.Client.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AAEICS.Client.Resources.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Incoming Certificates Today.
        /// </summary>
        public static string CreatedIncomingCertificatesTodayDashboardTitle {
            get {
                return ResourceManager.GetString("CreatedIncomingCertificatesTodayDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Issuance Certificates Today.
        /// </summary>
        public static string CreatedIssuanceCertificatesTodayDashboardTitle {
            get {
                return ResourceManager.GetString("CreatedIssuanceCertificatesTodayDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created acts of clarification of the sample/write-off today.
        /// </summary>
        public static string CreatedWtriteOffCertificatesTodayDashboardTitle {
            get {
                return ResourceManager.GetString("CreatedWtriteOffCertificatesTodayDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkThemeSettingsOption {
            get {
                return ResourceManager.GetString("DarkThemeSettingsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnLanguageSettingsOption {
            get {
                return ResourceManager.GetString("EnLanguageSettingsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC-ICS | Home.
        /// </summary>
        public static string HomeAppTitle {
            get {
                return ResourceManager.GetString("HomeAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeMenuOption {
            get {
                return ResourceManager.GetString("HomeMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightThemeSettingsOption {
            get {
                return ResourceManager.GetString("LightThemeSettingsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAE-ICS - SAFETY AND SECURITY.
        /// </summary>
        public static string MenuCopyright {
            get {
                return ResourceManager.GetString("MenuCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New incoming certificate.
        /// </summary>
        public static string NewCertificateMenuOption {
            get {
                return ResourceManager.GetString("NewCertificateMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC-ICS | New incoming certificate.
        /// </summary>
        public static string NewIncomingCertificateAppTitle {
            get {
                return ResourceManager.GetString("NewIncomingCertificateAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC-ICS | New issuance certificate.
        /// </summary>
        public static string NewIssuanceCertificateAppTitle {
            get {
                return ResourceManager.GetString("NewIssuanceCertificateAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Problems.
        /// </summary>
        public static string ProblemsDetectedDashboardTitle {
            get {
                return ResourceManager.GetString("ProblemsDetectedDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC-ICS | Record cards.
        /// </summary>
        public static string RecordCardAppTitle {
            get {
                return ResourceManager.GetString("RecordCardAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record cards.
        /// </summary>
        public static string RecordCardMenuOption {
            get {
                return ResourceManager.GetString("RecordCardMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC-ICS | Reports.
        /// </summary>
        public static string ReportsMenuAppTitle {
            get {
                return ResourceManager.GetString("ReportsMenuAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsMenuOption {
            get {
                return ResourceManager.GetString("ReportsMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC-ICS | Settings.
        /// </summary>
        public static string SettingsAppTitle {
            get {
                return ResourceManager.GetString("SettingsAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenuOption {
            get {
                return ResourceManager.GetString("SettingsMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string UkLanguageSettingsOption {
            get {
                return ResourceManager.GetString("UkLanguageSettingsOption", resourceCulture);
            }
        }
    }
}
